site_name: Dars Docs
site_description: The documentation for dars, the static site generator.
site_author: gusg21
theme: 'readable'
repo_url: https://github.com/darssites/dars/

pages:
  - Home: 'index.md'
  - Docs:
    - Getting Started: 'getting-started.md'
    - Classes: # The actual class-by-class docs
      - Paragraph: 'classes/paragraph.md'
      - Heading: 'classes/heading.md'
      - Link: 'classes/link.md'
      - Bold: 'classes/bold.md'
      - Code: 'classes/code.md'
      - Blockquote: 'classes/blockquote.md'
      - Anchor: 'classes/anchor.md'
      - Contact: 'classes/contact.md'
      - External: 'classes/external.md'
      - Image: 'classes/image.md'
      - Italics: 'classes/italics.md'
      - JScript: 'classes/jscript.md'
      - List: 'classes/list.md'
      - Mark: 'classes/mark.md'
      - Rule, Stylesheet, and Tags: 'classes/rule.md'
      - Scripted: 'classes/scripted.md'
